version: '3.8'
services:
  db:
    image: mariadb
    container_name: single-app_mariadb
    environment:
        MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    - single-app_data:/var/lib/mysql

volumes:
  single-app_data:

